# Tools 

## CEX's
Centralized Exchanges are a necessary evil in Web3. They can be used for trading and generally offer better rates and lower fee's than their decentralized counterparts. However they're generally not to be trusted as seen by some notable CEX failures in the not too distant past:

* Mt Gox (2014) - 850k BTC. $450 million in 2014 prices
* Bitfinex (2016) - 120k BTC. $72 million in 2016 prices
* Quadriga (2019) - $190 million in 2019 prices
* FTX (2022) - $8-10 billion in 2022 prices
* Celsius Network (2022) - $4.7 billion in 2022 prices
* BlockFi (2022) - $1-10 billion in 2022 prices
* Voyager Digital (2022) - $1.3 billion in 2022 prices

Notice how in 2022, contagion became pretty prevalent. 

## Wallets
A wallet is the primary way you interact with a [Blockchain](../technical/blockchains.qmd). 

Wallets have the following major attributes:

* Type - Hardware or Software wallets
* Private
* Platform - Mobile, Browser, Desktop or Hybrid
* [Application Model](../technical/blockchains.qmd#application-models) - Type of blockchains it supports. Can support multiple models. 

| Wallet Name | Type | Platform | Application Models Supported |
|-------------|------|-----------|----------------------------|
| [Ledger](https://www.ledger.com/) | Hardware | Desktop, Mobile | Account (EVM), UTXO, Specialized Account, Resource, Actor |
| [Trezor](https://trezor.io/) | Hardware | Desktop, Browser | Account (EVM), UTXO, Specialized Account |
| [MetaMask](https://metamask.io/) | Software | Browser Extension, Mobile | Account (EVM) |
| [Phantom](https://phantom.app/) | Software | Browser Extension, Mobile | Capability (Solana), Account (EVM), UTXO (Bitcoin) |
| [Safe](https://app.safe.global/welcome) | Software | Browser (Web App) | Account (EVM) |
| [TrustWallet](https://trustwallet.com/) | Software | Mobile | Account (EVM), UTXO, Specialized Account |
| [Rainbow](https://rainbow.me/en/) | Software | Mobile | Account (EVM) |

: Wallets {.striped .hover}

## Analysis Tools
There are numerous ways to analyze blockchains. 

* On chain analysis
* Data Professional Tools
    * Dashboards and Charting
    * SQL Playgrounds
    * API

On chain analysis tools allow you to analyze data on chain through a User Interface

### On Chain Analysis
#### Portfolio Trackers
We break down Portfolio Trackers into manual versus automated. Manual is whereby the user has to manually input their Tokens and how many they bought for how much USD.

Manual are recommended for newcomers, but they quickly fall down. They only handle Coins and Tokens and not your DeFi positions, such as Liquidity Pools, Money Market positions etc. They have a place and are valuable but Automated Portfolio Trackers are far superior and only getting better.

For Manual there are:

* [CoinGecko](https://www.coingecko.com/)
* [CoinMarketCap](https://coinmarketcap.com/)

For Automated, we need to break it down into single vs multiple [Application Model](../technical/blockchains.qmd#application-models) support.

| Portfolio Tracker | Supported Models | Key Features | Main Chains | Notable Aspects |
|------------------|------------------|--------------|-------------|-----------------|
| [DeBank](https://debank.com/) | Account (EVM) | - DeFi protocol tracking<br>- Wallet analytics<br>- Cross-chain support | Ethereum, BSC, Polygon, Avalanche | Strong focus on DeFi positions and yields |
| [Pulsar Finance](https://app.pulsar.finance/portfolio) | Account (EVM), UTXO, Capability Model, Cosmos | Support for the most chains. But values are often wrong |
| [Zapper](https://zapper.xyz/) | Account (EVM) | - NFT tracking<br>- DeFi dashboard<br>- Portfolio history | Ethereum, Optimism, Arbitrum, Polygon | Excellent UI/UX and bridging features |
| [Nansen Portfolio](https://app.nansen.ai/) | Account (EVM) | - Yield farming focus<br>- TVL tracking<br>- ROI calculator | All major EVM chains | Specializes in yield optimization |
| [DappRadar](https://dappradar.com/hub/wallet/) | Multiple Models | - NFT tracking<br>- DApp analytics<br>- Cross-chain support | Most major blockchains | Comprehensive ecosystem analytics |
| [Step Finance](https://app.step.finance/) | Capability Model | - Solana ecosystem<br>- Yield tracking<br>- NFT support | Solana | Native Solana portfolio manager |


: Portfolio-Tracker {.striped .hover}

I recommend newcomers to use Pulsar. As you learn about DeFi, you'll be chasing yield on numerous chains and will need something with the comprehensive coverage that only Pulsar provides. If you're only on EVM, then I recommend using Debank.

#### Explorers
Explorers allow you to explore transactions and on chain activity. 

I'll revise the table to be more focused and clear, removing the alternative explorers column.

| Blockchain | Primary Explorer | URL |
|------------|-----------------|-----|
| Bitcoin | Mempool Space | https://mempool.space/ |
| Ethereum | Etherscan | https://etherscan.io |
| ApeCoin | ApeScan | https://apescan.org |
| Arbitrum One | Arbiscan | https://arbiscan.io |
| Arbitrum Nova | Nova Explorer | https://nova.arbiscan.io |
| Base | BaseScan | https://basescan.org |
| Blast Chain | BlastScan | https://blastscan.io |
| BNB Chain | BscScan | https://bscscan.com |
| BTTC | BttcScan | https://bttcscan.com |
| Celo | CeloScan | https://celoscan.io |
| Cronos | CronoScan | https://cronoscan.com |
| Frax | FraxScan | https://fraxscan.io |
| Fantom | FTMScan | https://ftmscan.com |
| Gnosis | GnosisScan | https://gnosisscan.io |
| Linea | LineaScan | https://lineascan.build |
| Mantle | MantleScan | https://mantlescan.io |
| Moonbeam | Moonscan | https://moonbeam.moonscan.io |
| Moonriver | Moonscan | https://moonriver.moonscan.io |
| opBNB | opBNB Explorer | https://opbnbscan.com |
| Optimism | Optimistic Etherscan | https://optimistic.etherscan.io |
| Polygon zkEVM | Polygon zkEVM Explorer | https://zkevm.polygonscan.com |
| Polygon | PolygonScan | https://polygonscan.com |
| Scroll | ScrollScan | https://scrollscan.com |
| Avalanche | SnowTrace | https://snowtrace.io |
| Sophon | SophScan | https://sophonscan.com |
| Taiko | TakioScan | https://taikoscan.com |
| Wemix | WemixScan | https://wemixscan.com |
| Worldcoin | WorldScan | https://worldcoin.org/explorer |
| Xai | XaiScan | https://xaiscan.com |
| XDC | XdcScan | https://xdcscan.io |
| zkSync | zkSync Explorer | https://explorer.zksync.io |
| XRP | XRP Ledger Explorer | https://livenet.xrpl.org |
| Solana | Solana Explorer | https://explorer.solana.com |
| Dogecoin | DogeChain | https://dogechain.info |
| Cardano | Cardanoscan | https://cardanoscan.io |
| Tron | Tronscan | https://tronscan.org |
| TON | TON Explorer | https://tonscan.org |
| Polkadot | Polkascan | https://polkascan.io |
| Chainlink | Chainlink Explorer | https://explorer.chain.link |
| Stellar | Stellar Expert | https://stellar.expert |
| Bitcoin Cash | Blockchair | https://blockchair.com/bitcoin-cash |
| Sui | Sui Explorer | https://suiexplorer.com |
| NEAR | NEAR Explorer | https://explorer.near.org |
| Aptos | Aptos Explorer | https://explorer.aptoslabs.com |
| Hedera | HashScan | https://hashscan.io |
| Litecoin | Litecoin Explorer | https://litecoinblockexplorer.net |
| Internet Computer | IC Scan | https://icscan.io |
| VeChain | VeChain Stats | https://vechainstats.com |
| Filecoin | Filfox | https://filfox.info |
| Stacks | Stacks Explorer | https://explorer.stacks.co |
| Hyperliquid | Hyperliquid Explorer | https://hyperliquid.xyz/info |
| Kaspa | Kaspa Explorer | https://explorer.kaspa.org |
| Algorand | AlgoExplorer | https://algoexplorer.io |
| Cosmos | Mintscan | https://www.mintscan.io |
| Mantra | Mantra Scan | https://mantrascan.org |

: Explorers {.striped .hover}

##### Pure EVM 
Etherscan is the most widely used Explorer and has versions on all the major EVM Chains. We'll only focus on their Explorers for EVM chains in perpetuity or until something better comes along. 

I recommend using [Blockscan](https://blockscan.com/) which is from the same company and consolidates all their supported chains into a consolidated UI. It makes sense to use Blockscan for surface level analysis. But as soon as you want to delve into the code, you'll need to use one of their Explorers specializing on that particular chain. 

###### Exploring Solidity

We'll use [Etherscan](https://etherscan.io/) to explore the EVM

We'll delve into how to use Etherscan to analyze:

* Addresses 
* Contract

For Addresses we'll explore [Vitalik's Account](https://etherscan.io/address/0xab5801a7d398351b8be11c439e05c5b3259aec9b)

::: {.callout-note}
<blockquote class="twitter-tweet">
<a href="https://twitter.com/VitalikButerin/status/1050126908589887488"></a> 
</blockquote>
:::

Then for the Contract we'll explore [Tether's USDT](https://etherscan.io/address/0xdac17f958d2ee523a2206206994597c13d831ec7)

The first thing you need to know is that Solidity is a compiled language and as such for us to view the code in the Explorer, we need the developer to upload their code and have it verified against the bytecode. Don't sweat too much about the details, what you really want is to ensure that in the Etherscan explorer is the contract is verified. 

* Viewing the Solidity version
* Viewing the "standard" libraries the code inherits

#### Defillama
Defillama will become one of the most important tools you'll use in your degen journey. Give the team some love. 

### Data Professional Tools

#### API
We'll start off by using [Ortege](https://ortege.ai). For full transparency I own and founded Ortege. This Almanack can and will use data from any trusted source. But in the early days while we require data specifically tailored to our requirements, we will be using Ortege. Anyone contributing however can integrate with any other reputable data sources. 

We break down API's into the following categories:

* RPC Nodes. These are the API's provided by the [Blockchain clients](../technical/blockchains.qmd#clients). Each [Application Model](../technical/blockchains.qmd#application-models) will have a different API structure. The most famous example being the [Bitcon RPC standard](https://developer.bitcoin.org/reference/rpc/) and the [EVM RPC standard](https://eips.ethereum.org/EIPS/eip-1474)
* SQL based. These API's allow you to write SQL against their Datasets. Examples include [Dune](https://dune.com/) and [Flipside](https://flipsidecrypto.xyz/home/). Much like the RPC based API's, these will all have a different API structure. 
* Semantic Layer. Ortege is the first, that I'm aware of, API that aims to abstract away the blockchains implementation away from the developer and provide a uniform API that is consistent across blockchains.

##### Ortege
Coming Soon. 

## Security Tools

### OpenZeppelin 

## Privacy Tools

### VPN
The most commercially popular VPN's are ExpressVPN, NordVPN and CyberGhost. I'm not an expert here, but I use Mullvad VPN as it accepts BTC as payment and seems most resitant to state attacks. 

### TOR
