# Digital Assets

The logical place to start this Almanack is Digital Assets. These include all the financial instruments that exist within the Web3 sphere. For us to represent all Digital Assets within this space, it means we need to include all Web3 financial instruments, both on chain and off chain. 

We take inspiration from the [Fat Protocol Thesis](https://www.usv.com/writing/2016/08/fat-protocols/)[@monegro2016fat] to define the major categories of Digital Assets within the Web3 realm. We also adhere to the naming convention that stipulates Coins are digital assets relating to the running and operation of a Blockchain, whereas Tokens are digital assets that are issued on a Blockchain. 

We thus break down Digital Assets into the following Categories:

* Coins 
    * Primary Networks
    * Secondary Networks
        * Ozempic
        * Sugar
    * Derivatives
* Tokens 
    * Fungibles
    * Non Fungible

After describing the various categories and classes of Digital Assets we'll then delve into the Markets existing for these Digital Assets, as well as how an entity [hodls](../foundations/terms.qmd#hodl) the Digital Asset and the yield properties of the various types of Digital Assets. 

## Coins
This section deals primarily with Digital Assets as a Financial Instrument and as such any information relating to the technical makeup can be found in the [Blockchain](../technical/blockchains.qmd) documentation. 

### Network Economics
Token Models
Utility Tokens: Gas fees, staking, governance Security Tokens: Validator requirements, slashing deposits Network Tokens: Transaction fees, block rewards
Incentive Structures
Validator Rewards: Block rewards, transaction fees, staking yields User Incentives: Fee markets, priority mechanisms, rebate systems Developer Incentives: Grant programs, protocol fees, treasury funding
Economic Security
Minimum Stakes: Validator requirements, delegation minimums Slashing Conditions: Downtime penalties, malicious behavior penalties Market Making: Liquidity incentives, trading pair support

### Base Networks
This Almanack distinguishes between the financial properties of Coins versus the technical properties of a [Blockchain](../technical/blockchains.qmd). As such we don't refer to networks here by Layer 1 or Layer 2. That's a classification and distinction you can explore [here](../essentials/terms.qmd). 

We define a Base Network that maintains it's own Sovereignity. This means that the Coin on the network is used to economically secure the chain as well as final settlement to occur on this network. 

### Secondary Networks
These are networks that market themselves as settling the transactions on another network. The nuances of how they settle is covered under the [Blockchain chapter](../technical/blockchains.qmd). We'll encompass the full breadth of L2's including, but not limited to Plasma, Sidechains, Rollups etc. 

We then break these networks into Ozempic or Sugar networks. This reflects a hat tip to the Fat protocol metaphor. Ozempic networks are net extractors of value from their host chain, while Sugar networks cause the host chain to become fatter and therefore hold more value. 

Please see [Ozempic Effect](./ratings.qmd#ozempic-effect) to see how we determine if a network in a net ozempic or sugar network. 

### Derivatives

* On chain
    * Wrapped
        * Pure
        * Bridged
* Off Chain
    * Spot ETF's

#### On Chain Derivatives

#### Off Chain Derivatives

## Tokens

### Fungible
Fungible is a pretty terrible name, but it roughly means divisable. It's easier to explain via an example. If I have 10 dollars and I give you 3. I still have 7. It's divisable. If I have a car and I want to give you 30% of it, I cannot cut it up and give you a portion of it. It's Non fungible, or non divisable. There's more nuances which we can deal with in the vocabulary section. But that's the general idea of it. 

We have the following types:
* Stable Coins
    * Fiat backed
    * Crypto backed
    * Delta Neutral backed
* Shit Coins
    * Governance 
    * Meme
* Utility

Then we have numerous standards. We'll add only the most popular and relevant ones here.

Namely:
* ERC20
* ERC777
* ERC1363
* BRC20
* Runes
* Solana's SPL Token Standard
* ICS20

#### ICS20
The Inter-Chain Standard 20 is a [Cosmos](../financial/trollip_index.qmd#cosmos-hub) based standard for fungible token transfers between blockchains using the Inter-Blockchain Communication Protocol (IBC)

### Non Fungible
Has the following attributes:

* Art & Collectibles
* Profile Picture (PFP)
* Gaming
* Domain Names and Identity
* Real World Assets (RWA)


The NFT floor price is the lowest price at which an NFT from a particular collection is listed for sale on a marketplace. It serves as a benchmark for the collection's market value and is widely used to assess the entry point for potential buyers and to gauge the collection’s popularity and liquidity.

## Markets
Where can I buy these Digital Assets? The major markets are regulated and unregulated.

These are then divided into spot vs derivatives.

For regulated it's interesting as RedBelly in a blockchain, but it has KYC/AML. So is that regularly compliant. It's probably more truthful to break it down not by regulatory compliance, but anonymity. For if your on chain activity can be tracked then most mature jurisdictions will be able to force an individual to be compliant. 

## Hodling
Wallets

### Custodial

### Non-Custodial
* Pure
    * Cold
    * Hot
* Smart
    * MPC 
    * Smart Contract Based (Includes Account Abstraction)

## Yield Properties
Major categories are:

* Network Yield
* Trading Yield
* Protocol Yield


### Trading Yield
* Pricing appreciation
* Arbitrage Yield
    * Spot Arbitrage
    * Peg Arbitrage - These are unique to stable coins
* Options and Derivatives Premiums
* Futures funding rates

### Network Yield
* Mining Yield
    * Solo Mining
    * Pool Mining
    * Cloud Mining
* Validating Yield
    * Staking
* Network Fee Yield
    * Gas
* MEV
    * Toxic
    * Non Toxic
* Derivatives
    * Liquid Staking

### dApp Yield
* Staking
* Liquidity Provision
* Governance Participation
* NFT Rental Income

#### Liquidity Provision
We break this down into the following Categories

* AMM Pool fees
* Concentrated liquidity positions
* Order book market making
* Lending and Borrowing markets

##### Concentrated Liquidity Provision
Here we will break down rebalancing and focus on Loss Versus Rebalancing as per this paper https://arxiv.org/pdf/2208.06046
