bibliography: references.bib
book:
  author: Justin Trollip
  chapters:
  - index.qmd
  - intro.qmd
  - chapters:
    - ./content/essentials/terms.qmd
    - ./content/essentials/tools.qmd
    - ./content/essentials/memes.qmd
    - ./content/essentials/icons.qmd
    part: Web3 Essentials
  - chapters:
    - ./content/degen/scam.qmd
    - ./content/degen/starter.qmd
    - ./content/degen/giga.qmd
    part: Become a Degen
  - chapters:
    - ./content/financial/tokens.qmd
    - ./content/financial/ratings.qmd
    - ./content/financial/trollip_index.qmd
    part: Financial
  - chapters:
    - ./content/technical/cryptography.qmd
    - ./content/technical/blockchains.qmd
    - ./content/technical/dapps.qmd
    - ./content/technical/mev.qmd
    - ./content/technical/languages.qmd
    part: Technical
  - chapters:
    - ./content/social/governance.qmd
    part: Social
  - contributing.qmd
  - references.qmd
  date: v0.6.0
  page-navigation: true
  repo-url: https://github.com/HariSeldon23/degen-almanack
  search: true
  sharing:
  - twitter
  - linkedin
  - facebook
  title: Trollip's Degen Almanack
date: '2024-12-05'
format:
  html:
    code-fold: true
    highlight-style: github
    include-in-header:
      text: '<script async src="https://platform.twitter.com/widgets.js"></script>

        '
    number-sections: true
    theme: cosmo
    toc: true
    toc-depth: 3
  pdf:
    colorlinks: true
    documentclass: scrreprt
    keep-tex: false
    lof: false
    lot: false
    number-sections: true
    toc: true
project:
  output-dir: docs
  preview:
    browser: true
    navigate: true
    port: 4200
    watch-inputs: true
  render:
  - '*.qmd'
  - '!temp/'
  type: book
