bibliography: references.bib
book:
  author: Justin Trollip
  chapters:
  - chapters:
    - index.qmd
    - copyright.qmd
    - dedication.qmd
    - epigraph.qmd
    - preface.qmd
    - intro.qmd
    - ./content/intro/use.qmd
    - ./content/intro/terms.qmd
    part: Introduction
  - chapters:
    - ./content/foundations/foundations.qmd
    - ./content/foundations/path.qmd
    - ./content/foundations/alternatives.qmd
    - ./content/foundations/tools.qmd
    - ./content/foundations/basic_security.qmd
    part: Foundations
  - chapters: 
    - ./content/independence/independence.qmd
    - ./content/independence/first_steps.qmd
    - ./content/independence/fundamentals.qmd
    - ./content/independence/invest.qmd
    - ./content/independence/stables.qmd
    - ./content/independence/mid.qmd
    part: Path to Independence
  - chapters:
    - ./content/essentials/memes.qmd
    part: Web3 Essentials
  - chapters: 
    - ./content/technical/overview.qmd
    - ./content/technical/cryptography.qmd
    - ./content/technical/blockchains.qmd
    - ./content/technical/modular.qmd
    - ./content/technical/languages.qmd
    - ./content/technical/gas.qmd
    - ./content/technical/dapps.qmd
    - ./content/technical/mev.qmd
    part: Technologist's Path
  - chapters:
    - ./content/financial/tokens.qmd
    - ./content/financial/market_structure.qmd
    - ./content/financial/ratings.qmd
    - ./content/financial/trollip_index.qmd
    part: Financial
  - chapters:
    - ./content/social/governance.qmd
    part: Social
  - contributing.qmd
  - references.qmd
  date: '2024-12-09'
  page-navigation: true
  repo-url: https://github.com/HariSeldon23/degen-almanack
  search: true
  sharing:
  - twitter
  - linkedin
  - facebook
  title: Trollip's Degen Almanack
date: '2024-12-09'
format:
  html:
    code-fold: true
    highlight-style: github
    include-in-header:
      text: '<script async src="https://platform.twitter.com/widgets.js"></script>

        '
    number-sections: true
    theme: cosmo
    toc: true
    toc-depth: 3
  epub: 
    default: true
project:
  output-dir: docs
  preview:
    browser: true
    navigate: true
    port: 4200
    watch-inputs: true
  render:
  - '*.qmd'
  - '!temp/'
  type: book
