project:
  type: book

book:
  title: "Trollip's Web3 Almanack"
  author: "Justin Trollip"
  date: "12/2/2024"
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: "Web3 Essentials"
      chapters:
        - technolect.qmd
        - tools.qmd
        - rules.qmd
    
    - part: "Financial"
      chapters:
        - tokens.qmd
        - ratings.qmd
        - trollip_index.qmd
    
    - part: "Technical"
      chapters:
        - cryptography.qmd
        - blockchains.qmd
        - dapps.qmd
    
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt