project:
  type: book
  output-dir: docs
  preview:
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true
  render:
  - '*.qmd'
  - '!temp/'
book:
  title: Trollip's Degen Almanack
  author: Justin Trollip
  date: v0.4.0
  page-navigation: true
  search: true
  repo-url: https://github.com/HariSeldon23/degen-almanack
  sharing:
  - twitter
  - linkedin
  - facebook
  chapters:
  - index.qmd
  - intro.qmd
  - part: Web3 Essentials
    chapters:
    - ./content/essentials/terms.qmd
    - ./content/essentials/tools.qmd
    - ./content/essentials/memes.qmd
    - ./content/essentials/icons.qmd
  - part: Become a Degen
    chapters:
    - ./content/degen/scam.qmd
    - ./content/degen/starter.qmd
    - ./content/degen/giga.qmd
  - part: Financial
    chapters:
    - ./content/financial/tokens.qmd
    - ./content/financial/ratings.qmd
    - ./content/financial/trollip_index.qmd
  - part: Technical
    chapters:
    - ./content/technical/cryptography.qmd
    - ./content/technical/blockchains.qmd
    - ./content/technical/dapps.qmd
    - ./content/technical/mev.qmd
  - part: Social
    chapters:
    - ./content/social/governance.qmd
  - contributing.qmd
  - references.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    highlight-style: github
    include-in-header:
      text: '<script async src="https://platform.twitter.com/widgets.js"></script>

        '
  pdf:
    documentclass: scrreprt
    keep-tex: false
    toc: true
    number-sections: true
    colorlinks: true
    lot: false
    lof: false
