# Contributing

This Almanack will change often and get things wrong. It's only by being intellectually honest that it can ever hope to be the canonical guide to crypto and Web3. We follow Sophocles as our North Star

> "All men make mistakes, but a good man yields when he knows his course is wrong, and repairs the evil. The only crime is pride. "
Here we'll list all the outstanding contributions we're looking for.

I'll also use it as a dumping ground where I can keep track of things I need to read to include:

* https://bitcoinrollups.org/
* https://tr3y.io/articles/crypto/bitcoin-zk-rollups.html

## Current requirements
### Translations
Be good to focus on the most widely spoken languages first. So 

* Mandarin
* Hindi
* Spanish
* French
* Arabic
* Bengali
* Russian
* Portuguese
* Indonesian

### Data Dynamism 
I'd like an easy way to embed live data in every version publish. So for example if I want to reference the current ETH price, I should be able to do something like {{eth.current_price}} and it will embed the current price during the Quarto render with the latest price. 