# Big brain

## Converting FIAT into a Cryptocurrency anonymously 

This may be the hardest part of being a Degen. A Degen values privacy. Important to distinguish there is a difference between privacy and secrecy. I'd like my cryptocurrency to display the same characteristics as cash. A means of exchange that has been working just fine for centuries. Cash is private by default and people have seemed pretty happy with that arrangement for over 3 centuries. 

The hardest part of ensuring privacy is making sure that when you create a new wallet there is no trace back to your off chain identity.

The two biggest footprints you can leave are:

1. Funding your wallet to pay for Gas
2. Receiving funds in your wallet from a compromised account

When funding your on chain wallet from a CEX, it becomes very easy to trace your identity. Almost all CEX's require you to KYC. So when you transfer $10 of ETH into your Metamask wallet, anyone will be able to find out that the funding of the wallet came from a CEX and via the CEX will be able to link your identity to your wallet.

So currently the best way to do this is:

* Create two wallets. Compromised and Clean
* Save the Private Keys
* Connect to your VPN
* TOR doesn't support add ons, so we can't install a wallet, but rather need to run a script in order to shield our funds


We can also try Railgun. I'll run through both Tornado and Railgun and eventually Payy wallet and then based upon the results of all those experiments I'll make a recommendation about the best approach to obtain a private by default wallet. 

* Purchase USDC or USDT from a CEX
* Transfer the stable coins to the throwaway account
* Download [Railgun Client](https://www.railway.xyz/#download)
* Create a Shielded Address
* Transfer it in common increments similar to how Tornado Cash to the clean wallet at random intervals

