# Gigabrain Degen

## Converting FIAT into a Cryptocurrency

This may be the hardest part of being a Degen. A Degen values privacy. Important to distinguish there is a difference between privacy and secrecy. I'd like my cryptocurrency to display the same characteristics as cash. A means of exchange that has been working just fine for centuries. Cash is private by default and people have seemed pretty happy with that arrangement for over 3 centuries. 

Currently the best way to do this is via:

* [Bisq](https://bisq.network/)
* [HODL HODL](https://hodlhodl.com/)

Bisq has terrible rates, so I recommend Hodl Hodl. Else another alternative that will work just as well is:

* Create two new accounts on an Ethereum Layer 2. 1 that you'll throw away and one that will be secure
* Purchase USDC or USDT from a CEX
* Transfer the stable coins to the throwaway account
* Download [Railgun Client](https://www.railway.xyz/#download)
* Create a Shielded Address
* Transfer it in common increments similar to how Tornado Cash to the clean wallet at random intervals

