# .github/workflows/auto-version.yml
name: Auto Version and Deploy
on:
  push:
    branches:
      - main

jobs:
  version-and-deploy:
    runs-on: ubuntu-latest
    
    # Define the permissions needed for this workflow
    permissions:
      contents: write
      
    steps:
      # For the initial checkout, we'll use the default GITHUB_TOKEN
      - uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml semver
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin texlive-xetex texlive-fonts-recommended texlive-extra-utils
          
      - name: Verify SVG conversion tool
        run: |
          which rsvg-convert || echo "rsvg-convert not found"
          rsvg-convert --version || echo "rsvg-convert not working"
          
      - name: Bump version
        id: bump-version
        run: |
          python .github/scripts/bump_version.py minor
          echo "NEW_VERSION=$(cat version.txt)" >> $GITHUB_ENV
          
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install TinyTeX
        run: |
          quarto install tinytex
          
      - name: Render Book
        run: |
          quarto render
          
      - name: Handle PDF
        run: |
          if [ -f "docs/Trollip-s-Degen-Almanack.pdf" ]; then
            cp "docs/Trollip-s-Degen-Almanack.pdf" "docs/Trollip-s-Degen-Almanack-v${NEW_VERSION}.pdf"
          else
            echo "PDF files in docs:"
            find docs -name "*.pdf"
            exit 1
          fi
          
      # Separate authentication step for clarity
      - name: Prepare git credentials
        env:
          GITHUB_TOKEN: ${{ secrets.degen_almanack_version_publish }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          echo "https://$GITHUB_TOKEN@github.com" > ~/.git-credentials
          git config --global credential.helper store
          
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.degen_almanack_version_publish }}
        run: |
          # Add all changes including new PDFs
          git add version.txt _quarto.yml docs/
          
          # Create commit
          git commit -m "Auto version bump and build [skip ci]"
          
          # Push using the stored credentials
          git push origin HEAD:main