# .github/workflows/auto-version.yml
name: Auto Version and Deploy
on:
  push:
    branches:
      - main
  
jobs:
  version-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml semver
          
      - name: Bump version
        id: bump-version
        run: |
          python .github/scripts/bump_version.py minor
          
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install TinyTeX
        run: |
          quarto install tinytex
          
      - name: Render Book
        run: |
          quarto render
          
      - name: Generate PDF with version
        run: |
          VERSION=$(cat version.txt)
          cp docs/Trollip_s-Degen-Almanack.pdf "docs/Trollip_s-Degen-Almanack-v${VERSION}.pdf"
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add version.txt _quarto.yml docs/
          git commit -m "Auto version bump and build [skip ci]"
          git push