# .github/workflows/auto-version.yml
name: Auto Version and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: read # This sets the base permissions for the GITHUB_TOKEN

jobs:
  version-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # For fine-grained PATs, we don't specify the token in the checkout action
          # This allows it to use the default GITHUB_TOKEN for reading
          
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml semver
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin texlive-xetex texlive-fonts-recommended texlive-extra-utils
          
      - name: Verify SVG conversion tool
        run: |
          which rsvg-convert || echo "rsvg-convert not found"
          rsvg-convert --version || echo "rsvg-convert not working"
          
      - name: Bump version
        id: bump-version
        run: |
          python .github/scripts/bump_version.py minor
          echo "NEW_VERSION=$(cat version.txt)" >> $GITHUB_ENV
          
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install TinyTeX
        run: |
          quarto install tinytex
          
      - name: Render Book
        run: |
          quarto render
          
      - name: Handle PDF
        run: |
          if [ -f "docs/Trollip-s-Degen-Almanack.pdf" ]; then
            cp "docs/Trollip-s-Degen-Almanack.pdf" "docs/Trollip-s-Degen-Almanack-v${NEW_VERSION}.pdf"
          else
            echo "PDF files in docs:"
            find docs -name "*.pdf"
            exit 1
          fi
          
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.degen_almanack_version_publish }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          # For fine-grained PATs, we need to set up the remote differently
          git remote set-url origin "https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git"
          
          git add version.txt _quarto.yml docs/
          git commit -m "Auto version bump and build [skip ci]"
          git push