name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # Get the latest code
      - uses: actions/checkout@v3
      
      # Set up Quarto - this is the main tool we need for building the book
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      # Install TinyTeX for PDF support - needed for some Quarto features
      - name: Install TinyTeX
        run: |
          quarto install tinytex
      
      # Build the book with Quarto
      - name: Build Book
        run: |
          quarto render
      
      # Only deploy if this is a push to main (not a PR)
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages