name: Build and Deploy HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      # Build the book with Quarto - HTML only
      - name: Build Book
        run: |
          quarto render --to html
      
      # Deploy to GitHub Pages if this is a push to main
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages